#!/usr/bin/env bash
# Run the Cuttle daemon as a headless systemd *user* service (Linux server Host).
# Guide: docs/guides/HEADLESS_SERVER.md
#
#   cuttle-service.sh print       # show the unit this checkout would install
#   cuttle-service.sh install     # write + enable + start (and enable linger)
#   cuttle-service.sh uninstall   # stop + disable + remove the unit
#   cuttle-service.sh status      # systemctl status + recent journal
#
# Run from a normal login shell: install captures your current PATH so vendor
# CLIs (agent, codex, claude, muse, …) resolve the same way under systemd.
set -euo pipefail

UNIT_NAME="cuttle.service"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"

systemd_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//%/%%}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "$value"
}

render_unit() {
  # Environment=/WorkingDirectory= expand % specifiers, but not $ variables.
  # ExecStart= also expands $, so escape it only in the command path.
  local root_path path_quoted exec_quoted
  root_path="${PROJECT_ROOT//%/%%}"
  path_quoted="$(systemd_quote "PATH=$PATH")"
  exec_quoted="$(systemd_quote "${PROJECT_ROOT//\$/\$\$}/start_cuttle.sh")"
  cat <<EOF
# Generated by .cuttle/scripts/cuttle-service.sh — re-run "install" to refresh.
[Unit]
Description=Cuttle daemon (headless Host)
Documentation=$(systemd_quote "file://$PROJECT_ROOT/docs/guides/HEADLESS_SERVER.md")

[Service]
Type=simple
WorkingDirectory=$root_path
Environment=$path_quoted
Environment=PYTHONUNBUFFERED=1
# User managers can't order after network-online.target; wait (max 30s) for a
# route so the LAN IP is known when Flask builds its CORS allowlist.
ExecStartPre=/bin/sh -c 'n=0; until ip route get 1.1.1.1 >/dev/null 2>&1 || [ \$\$n -ge 30 ]; do n=\$\$((n+1)); sleep 1; done'
ExecStart=$exec_quoted --no-tray --no-ui
# SIGTERM only the daemon so it stops Flask and agent runs itself.
KillMode=mixed
TimeoutStopSec=45
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
}

require_systemd() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl not found — this helper needs systemd." >&2
    exit 1
  fi
}

cmd_install() {
  require_systemd
  if [[ ! -x "$PROJECT_ROOT/start_cuttle.sh" ]]; then
    echo "Missing or non-executable $PROJECT_ROOT/start_cuttle.sh" >&2
    exit 1
  fi
  if pgrep -f 'cuttle_daemon\.py' >/dev/null 2>&1 \
     && ! systemctl --user is-active --quiet "$UNIT_NAME"; then
    echo "A cuttle_daemon is already running outside systemd." >&2
    echo "Stop it first (tray Exit / Electron Host quit), then re-run install." >&2
    exit 1
  fi
  mkdir -p "$UNIT_DIR"
  render_unit >"$UNIT_PATH"
  echo "Wrote $UNIT_PATH"
  systemctl --user daemon-reload
  systemctl --user enable --now "$UNIT_NAME"
  if command -v loginctl >/dev/null 2>&1; then
    if [[ "$(loginctl show-user "$USER" -p Linger --value 2>/dev/null)" != "yes" ]]; then
      echo "Enabling linger so Cuttle starts at boot without a login (may prompt for sudo)..."
      loginctl enable-linger "$USER" || sudo loginctl enable-linger "$USER"
    fi
  fi
  systemctl --user --no-pager status "$UNIT_NAME" | head -n 12 || true
}

cmd_uninstall() {
  require_systemd
  systemctl --user disable --now "$UNIT_NAME" 2>/dev/null || true
  rm -f "$UNIT_PATH"
  systemctl --user daemon-reload
  echo "Removed $UNIT_PATH (linger left as-is; 'loginctl disable-linger $USER' to undo)."
}

cmd_status() {
  require_systemd
  systemctl --user --no-pager status "$UNIT_NAME" || true
  echo
  journalctl --user -u "$UNIT_NAME" -n 30 --no-pager || true
}

case "${1:-}" in
  print) render_unit ;;
  install) cmd_install ;;
  uninstall) cmd_uninstall ;;
  status) cmd_status ;;
  *)
    sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
    ;;
esac
