#!/usr/bin/env python3
"""
Setup script for JamBit OS environment variables.
This script helps you create the .env file with the necessary configuration.
"""

import os
from pathlib import Path

def create_env_file():
    """Create .env file with user input"""
    env_file = Path(".env")
    
    if env_file.exists():
        print("WARNING: .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    print("JamBit OS Environment Setup")
    print("=" * 40)
    print("This script will help you create the .env file with necessary configuration.")
    print()
    
    # Get Discord Bot Token
    print("1. Discord Bot Configuration")
    print("   - Go to https://discord.com/developers/applications")
    print("   - Create a new application or select existing one")
    print("   - Go to 'Bot' section and copy the token")
    discord_token = input("   Enter your Discord Bot Token: ").strip()
    
    # Get Owner ID
    print("\n2. Owner ID Configuration")
    print("   - In Discord, enable Developer Mode (User Settings > Advanced > Developer Mode)")
    print("   - Right-click your username and select 'Copy User ID'")
    owner_id = input("   Enter your Discord User ID: ").strip()
    
    # Get OpenAI API Key (Optional)
    print("\n3. OpenAI API Configuration (Optional)")
    print("   - Go to https://platform.openai.com/api-keys")
    print("   - Create a new API key")
    print("   - Leave blank to skip (bot will work with basic commands only)")
    openai_key = input("   Enter your OpenAI API Key (or press Enter to skip): ").strip()
    
    # Create .env content
    env_content = f"""# JamBit OS Environment Variables
# Generated by setup_env.py

# Discord Bot Configuration
DISCORD_TOKEN={discord_token}
OWNER_ID={owner_id}

# OpenAI API Configuration (Optional)
# Leave empty to disable AI features - bot will still work with basic commands
OPENAI_API_KEY={openai_key}

# Optional: Additional Configuration
# BOT_PREFIX=!
# DEBUG_MODE=false
"""
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"\nSUCCESS: .env file created successfully!")
        print(f"Location: {env_file.absolute()}")
        print("\nSetup complete! You can now run the bot.")
        print("\nNext steps:")
        print("1. Run: python launcher.py")
        print("2. Or run: python bot_deprecated.py (Discord bot only)")
        print("3. Or run: python web_chat_api.py (Web API only)")
        
    except Exception as e:
        print(f"\nERROR: Error creating .env file: {e}")
        print("Please create the file manually with the following content:")
        print("\n" + "="*50)
        print(env_content)
        print("="*50)

def check_dependencies():
    """Check if required dependencies are installed"""
    print("Checking dependencies...")
    
    required_packages = [
        'discord.py',
        'openai', 
        'python-dotenv',
        'flask',
        'flask-cors',
        'psutil',
        'pyautogui',
        'mss',
        'pytesseract'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            if package == 'discord.py':
                import discord
            elif package == 'python-dotenv':
                import dotenv
            elif package == 'flask-cors':
                import flask_cors
            else:
                __import__(package.replace('-', '_'))
            print(f"  OK: {package}")
        except ImportError:
            print(f"  MISSING: {package}")
            missing_packages.append(package)
    
    if missing_packages:
        print(f"\nWARNING: Missing packages: {', '.join(missing_packages)}")
        print("Install them with: pip install " + " ".join(missing_packages))
        return False
    else:
        print("\nSUCCESS: All dependencies are installed!")
        return True

if __name__ == "__main__":
    print("JamBit OS Setup Script")
    print("=" * 30)
    
    # Check dependencies first
    deps_ok = check_dependencies()
    
    if not deps_ok:
        print("\nWARNING: Please install missing dependencies before continuing.")
        response = input("Continue anyway? (y/N): ").strip().lower()
        if response != 'y':
            exit(1)
    
    print("\n" + "="*50)
    create_env_file()
